/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as LegalTermsIndexRouteImport } from './routes/legal.terms/index'
import { Route as LegalPrivacyIndexRouteImport } from './routes/legal.privacy/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsIndexRoute = LegalTermsIndexRouteImport.update({
  id: '/legal/terms/',
  path: '/legal/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyIndexRoute = LegalPrivacyIndexRouteImport.update({
  id: '/legal/privacy/',
  path: '/legal/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpIndexRoute
  '/legal/privacy': typeof LegalPrivacyIndexRoute
  '/legal/terms': typeof LegalTermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpIndexRoute
  '/legal/privacy': typeof LegalPrivacyIndexRoute
  '/legal/terms': typeof LegalTermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help/': typeof HelpIndexRoute
  '/legal/privacy/': typeof LegalPrivacyIndexRoute
  '/legal/terms/': typeof LegalTermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/help' | '/legal/privacy' | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/help' | '/legal/privacy' | '/legal/terms'
  id: '__root__' | '/' | '/help/' | '/legal/privacy/' | '/legal/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  LegalPrivacyIndexRoute: typeof LegalPrivacyIndexRoute
  LegalTermsIndexRoute: typeof LegalTermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms/': {
      id: '/legal/terms/'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy/': {
      id: '/legal/privacy/'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  LegalPrivacyIndexRoute: LegalPrivacyIndexRoute,
  LegalTermsIndexRoute: LegalTermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
